//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationApp.Laboratory.UserControl {
    
    
    public partial class UserControl_LabOrderDetails {
        
        /// <summary>
        /// txtlabnumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::System.Web.UI.WebControls.TextBox txtlabnumber;
        
        /// <summary>
        /// txtSpecLabOrderdt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::Telerik.Web.UI.RadDatePicker txtSpecLabOrderdt;
    }
}
