pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["add_an_entry_in_a_custom_list.htm","Administration &#62; Custom Lists &#62; Add an Entry in a Custom List","Add an Entry in a Custom List",""],
["change_list_entry_priority.htm","Administration &#62; Custom Lists &#62; Change List Entry Priority","Change List Entry Priority",""],
["custom_reports.htm","Custom Reports","Custom Reports",""],
["hiv_exposed_infant_fu_card.htm","HIV Exposed Infant Follow up Card","HIV Exposed Infant Follow up Card",""],
["iqcare_configuration.htm","IQCare Configuration and Administration","IQCare Configuration and Administration ",""],
["pasdpadd_a_patient.htm","Find/Add Patient &#62; Add a New Patient","Add a New Patient",""],
["pasdpadministration.htm","Administration","Administration",""],
["pasdpbackup_database.htm","Administration &#62; Backup Database","Backup Database",""],
["pasdpcare_ended.htm","Clinical Forms &#62; Care Ended","Care Ended",""],
["pasdpclinical_forms.htm","Clinical Forms","Clinical Forms",""],
["pasdpconfigure_audit_trail.htm","Administration &#62; Configure Audit Trail","Configure Audit Trail",""],
["pasdpconfigure_care_ended_form.htm","Administration &#62; Configure Care Ended Form","Configure Care Ended Form",""],
["pasdpcustom_lists.htm","Administration &#62; Custom Lists","Custom Lists",""],
["pasdpdata_dictionary.htm","Data Dictionary","Data Dictionary",""],
["pasdpfacility_statistics.htm","Reports &#62; Facility Statistics","Facility Statistics",""],
["pasdpfind_add_patient.htm","Find/Add Patient","Find/Add Patient",""],
["pasdpfind_a_patient.htm","Find/Add Patient &#62; Find a Patient","Find a Patient",""],
["pasdpimmunisations.htm","Clinical Forms &#62; Immunisations","Immunisations",""],
["pasdpintegration_with_delta_9.htm","Integration with Delta 9","Integration with Delta 9",""],
["pasdpiqcare-padmt_data_entry_flow.htm","IQCare-PADMT Data Entry Flow","IQCare-PADMT Data Entry Flow",""],
["pasdpiqcare-padmt_support.htm","IQCare-PADMT Support","IQCare-PADMT Support",""],
["pasdplaboratory.htm","Clinical Forms &#62; Laboratory","Laboratory",""],
["pasdplab_alert_business_rules.htm","Lab Alert Business Rules","Lab Alert Business Rules",""],
["pasdpnon-visit_clinic_note.htm","Clinical Forms &#62; Non-Visit Clinic Note","Non-Visit Clinic Note",""],
["pasdppadmt_overview.htm","IQCare-PADMT Overview","IQCare-PADMT Overview",""],
["pasdppatient_home_page_explained.htm","Patient Home Page Explained","Patient Home Page Explained",""],
["pasdppatient_slider.htm","Patient Slider","Patient Slider",""],
["pasdppatient_visit_summary.htm","Reports &#62; Patient Visit Summary","Patient Visit Summary",""],
["pasdppharmacy.htm","Clinical Forms &#62; Pharmacy","Pharmacy",""],
["pasdpregistration.htm","Clinical Forms &#62; Registration","Registration",""],
["pasdpreports.htm","Reports","Reports",""],
["pasdpsearch_for_a_patient.htm","Find/Add Patient &#62; Search For A Patient","Search For A Patient",""],
["pasdpusing_touch_features.htm","Using Touch Features","Using Touch Features",""],
["pasdpview_existing_forms.htm","View Existing Forms","View Existing Forms",""],
["pasdpvisit.htm","Clinical Forms &#62; Visit","Visit",""],
["patientlevelfeatures.htm","Patient Level Features","Patient Level Features",""],
["predefinedreports.htm","Pre-Defined Reports","Pre-Defined Reports",""],
["scheduler.htm","Appointment Scheduler","Appointment Scheduler",""],
["update_an_entry_in_a_restricted_custom_list.htm","Administration &#62; Custom Lists &#62; Update an Entry in a Custom List","Update an Entry in a  Custom List",""]];
